#pragma once

#define CHOWDSP_SLIDES_MACOS __APPLE__
#define CHOWDSP_SLIDES_LINUX __linux__
#define CHOWDSP_SLIDES_WINDOWS defined(_WIN64)
#define CHOWDSP_SLIDES_WEB __EMSCRIPTEN__
#define CHOWDSP_SLIDES_POSIX CHOWDSP_SLIDES_MACOS || CHOWDSP_SLIDES_LINUX || CHOWDSP_SLIDES_WEB
